# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_person.ipynb.

# %% auto 0
__all__ = []

# %% ../nbs/00_person.ipynb 5
from mesa import Agent, Model
from mesa.time import RandomActivation
from mesa.space import MultiGrid
from mesa.datacollection import DataCollector
import random
